package vpn

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func quiet() *slog.Logger { return slog.New(slog.NewTextHandler(io.Discard, nil)) }

// A provider's file, with the things they actually put in one: a comment, a
// second address, two DNS servers, a hostname endpoint and a keepalive.
const providerConf = `
# Generated by a provider
[Interface]
PrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=
Address = 10.64.0.2/32, fc00:bbbb:bbbb:bb01::1:1/128
DNS = 10.64.0.1, 1.1.1.1
MTU = 1380

[Peer]
PublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=
PresharedKey = 5DdG8pMWvCk1GgSPtMh6Tpg09QqBqBQMlkjqDVYd8kU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = se-mma-wg-001.example.com:51820
PersistentKeepalive = 25
`

func TestParseConfigReadsAProviderFile(t *testing.T) {
	cfg, err := ParseConfig(providerConf)
	if err != nil {
		t.Fatalf("ParseConfig: %v", err)
	}

	if len(cfg.Addresses) != 2 {
		t.Errorf("Addresses = %v, want both of them", cfg.Addresses)
	}
	if got := cfg.Addresses[0].String(); got != "10.64.0.2" {
		t.Errorf("Address = %q, want the address without its prefix length", got)
	}
	if len(cfg.DNS) != 2 {
		t.Errorf("DNS = %v, want two servers", cfg.DNS)
	}
	if cfg.MTU != 1380 {
		t.Errorf("MTU = %d, want the file's 1380", cfg.MTU)
	}
	if cfg.Endpoint != "se-mma-wg-001.example.com:51820" {
		t.Errorf("Endpoint = %q, want it verbatim", cfg.Endpoint)
	}
	if len(cfg.AllowedIPs) != 2 {
		t.Errorf("AllowedIPs = %v, want both families", cfg.AllowedIPs)
	}
	if cfg.Keepalive != 25 {
		t.Errorf("Keepalive = %d, want 25", cfg.Keepalive)
	}
}

// The UAPI is hex where the file is base64, and getting that wrong produces a
// device that comes up, configures cleanly, and never handshakes.
func TestUAPIConvertsKeysToHex(t *testing.T) {
	cfg, err := ParseConfig(providerConf)
	if err != nil {
		t.Fatalf("ParseConfig: %v", err)
	}
	uapi, err := cfg.uapi("192.0.2.10:51820")
	if err != nil {
		t.Fatalf("uapi: %v", err)
	}

	for _, want := range []string{
		"private_key=a8546de3f8032e117a5558cb3d3f4bd0c90dcbcc9eab74ba2dcebf3d7b12b364",
		"public_key=a431a09eb205f2a2e0dcc9c6e69324899d4ba8f9c501c74c3b13708fe6e1d07a",
		"preshared_key=",
		"endpoint=192.0.2.10:51820",
		"persistent_keepalive_interval=25",
		"allowed_ip=0.0.0.0/0",
		"allowed_ip=::/0",
		"replace_peers=true",
	} {
		if !strings.Contains(uapi, want) {
			t.Errorf("uapi is missing %q:\n%s", want, uapi)
		}
	}
	// The file's own base64 must not appear anywhere in what is sent.
	if strings.Contains(uapi, cfg.PrivateKey) {
		t.Error("the base64 private key was passed straight through to the device")
	}
}

// Each of these brings up a device that can never work, and each fails with the
// field named rather than as "invalid argument" three layers down.
func TestParseConfigRefusesTheUnusable(t *testing.T) {
	for name, conf := range map[string]string{
		"no private key": "[Interface]\nAddress = 10.0.0.2/32\n[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = a:1",
		"no public key":  "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\n[Peer]\nEndpoint = a:1",
		"no endpoint":    "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\n[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=",
		"no address":     "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\n[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = a:1",
		"endpoint has no port": "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\n" +
			"[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = vpn.example.com",
		"key is not 32 bytes": "[Interface]\nPrivateKey = c2hvcnQ=\nAddress = 10.0.0.2/32\n" +
			"[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = a:1",
		"MTU is nonsense": "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\nMTU = enormous\n" +
			"[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = a:1",
	} {
		if _, err := ParseConfig(conf); err == nil {
			t.Errorf("%s: ParseConfig accepted it", name)
		}
	}
}

// wg-quick files carry directives that describe a kernel interface. A userspace
// tunnel has none of those things, and a provider's file must still work.
func TestParseConfigIgnoresWhatItCannotDo(t *testing.T) {
	conf := providerConf + "\n[Interface]\nTable = off\nPostUp = iptables -A FORWARD -j ACCEPT\nSaveConfig = true\n"
	if _, err := ParseConfig(conf); err != nil {
		t.Fatalf("ParseConfig rejected a directive it should ignore: %v", err)
	}
}

func TestParseConfigDefaults(t *testing.T) {
	cfg, err := ParseConfig("[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\n" +
		"[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = 192.0.2.1:51820\n")
	if err != nil {
		t.Fatalf("ParseConfig: %v", err)
	}
	if cfg.MTU != DefaultMTU {
		t.Errorf("MTU = %d, want the %d default", cfg.MTU, DefaultMTU)
	}
	if len(cfg.AllowedIPs) != 1 || cfg.AllowedIPs[0].String() != "0.0.0.0/0" {
		t.Errorf("AllowedIPs = %v, want a full tunnel by default", cfg.AllowedIPs)
	}
}

// exitAddress has to read both shapes, because the URL is configurable and
// somebody will point it at the other kind.
func TestExitAddressReadsBothShapes(t *testing.T) {
	for name, body := range map[string]string{
		"cloudflare trace": "fl=123abc\nh=www.cloudflare.com\nip=203.0.113.9\nts=1.0\n",
		"bare address":     "203.0.113.9\n",
	} {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			fmt.Fprint(w, body)
		}))

		got, err := exitAddress(context.Background(), srv.Client(), srv.URL)
		if err != nil {
			t.Errorf("%s: %v", name, err)
		} else if got != "203.0.113.9" {
			t.Errorf("%s: exitAddress = %q, want 203.0.113.9", name, got)
		}
		srv.Close()
	}
}

func TestExitAddressRejectsNonsense(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		fmt.Fprint(w, "<html>your ISP's captive portal</html>")
	}))
	defer srv.Close()

	if _, err := exitAddress(context.Background(), srv.Client(), srv.URL); err == nil {
		t.Fatal("exitAddress accepted a page with no address in it")
	}
}

// --- the honest floor, for a client curator does not route -------------------

func TestExternalGuard(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		fmt.Fprint(w, "ip=203.0.113.9\n")
	}))
	defer srv.Close()

	says := func(addr string) func(context.Context) (string, error) {
		return func(context.Context) (string, error) { return addr, nil }
	}

	t.Run("same address refuses", func(t *testing.T) {
		err := External(says("203.0.113.9"), srv.URL, srv.Client(), quiet())(context.Background())
		if err == nil {
			t.Fatal("dispatch was allowed to a client on curator's own exit address")
		}
		if !strings.Contains(err.Error(), "203.0.113.9") {
			t.Errorf("err = %q, want it to name the address", err)
		}
	})

	t.Run("different address passes", func(t *testing.T) {
		if err := External(says("198.51.100.7"), srv.URL, srv.Client(), quiet())(context.Background()); err != nil {
			t.Errorf("dispatch refused for a client that is clearly somewhere else: %v", err)
		}
	})

	// A client that has never talked to a swarm has nothing to report, and
	// refusing the first dispatch on a fact that only exists after one is a
	// deadlock with a security-shaped excuse.
	t.Run("unknown address passes with a warning", func(t *testing.T) {
		if err := External(says(""), srv.URL, srv.Client(), quiet())(context.Background()); err != nil {
			t.Errorf("dispatch refused for a client with no address yet: %v", err)
		}
	})

	t.Run("an unreachable client is an error, not a pass", func(t *testing.T) {
		fails := func(context.Context) (string, error) { return "", errors.New("connection refused") }
		if err := External(fails, srv.URL, srv.Client(), quiet())(context.Background()); err == nil {
			t.Fatal("a client that could not be asked was treated as protected")
		}
	})
}

// Required is the default posture with the embedded engine and no tunnel: a
// refusal that names the variable which fixes it.
func TestRequiredNamesTheVariable(t *testing.T) {
	err := Required()(context.Background())
	if err == nil {
		t.Fatal("Required allowed a dispatch")
	}
	for _, want := range []string{"VPN_CONFIG", "VPN_REQUIRED=false"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("err = %q, want it to mention %s", err, want)
		}
	}
}
