package vpn

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"net/http/httptest"
	"net/netip"
	"strings"
	"testing"
	"time"
)

func quiet() *slog.Logger { return slog.New(slog.NewTextHandler(io.Discard, nil)) }

// A provider's file, with the things they actually put in one: a comment, a
// second address, two DNS servers, a hostname endpoint and a keepalive.
const providerConf = `
# Generated by a provider
[Interface]
PrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=
Address = 10.64.0.2/32, fc00:bbbb:bbbb:bb01::1:1/128
DNS = 10.64.0.1, 1.1.1.1
MTU = 1380

[Peer]
PublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=
PresharedKey = 5DdG8pMWvCk1GgSPtMh6Tpg09QqBqBQMlkjqDVYd8kU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = se-mma-wg-001.example.com:51820
PersistentKeepalive = 25
`

func TestParseConfigReadsAProviderFile(t *testing.T) {
	cfg, err := ParseConfig(providerConf)
	if err != nil {
		t.Fatalf("ParseConfig: %v", err)
	}

	if len(cfg.Addresses) != 2 {
		t.Errorf("Addresses = %v, want both of them", cfg.Addresses)
	}
	if got := cfg.Addresses[0].String(); got != "10.64.0.2" {
		t.Errorf("Address = %q, want the address without its prefix length", got)
	}
	if len(cfg.DNS) != 2 {
		t.Errorf("DNS = %v, want two servers", cfg.DNS)
	}
	if cfg.MTU != 1380 {
		t.Errorf("MTU = %d, want the file's 1380", cfg.MTU)
	}
	if cfg.Endpoint != "se-mma-wg-001.example.com:51820" {
		t.Errorf("Endpoint = %q, want it verbatim", cfg.Endpoint)
	}
	if len(cfg.AllowedIPs) != 2 {
		t.Errorf("AllowedIPs = %v, want both families", cfg.AllowedIPs)
	}
	if cfg.Keepalive != 25 {
		t.Errorf("Keepalive = %d, want 25", cfg.Keepalive)
	}
}

// The UAPI is hex where the file is base64, and getting that wrong produces a
// device that comes up, configures cleanly, and never handshakes.
func TestUAPIConvertsKeysToHex(t *testing.T) {
	cfg, err := ParseConfig(providerConf)
	if err != nil {
		t.Fatalf("ParseConfig: %v", err)
	}
	uapi, err := cfg.uapi("192.0.2.10:51820")
	if err != nil {
		t.Fatalf("uapi: %v", err)
	}

	for _, want := range []string{
		"private_key=a8546de3f8032e117a5558cb3d3f4bd0c90dcbcc9eab74ba2dcebf3d7b12b364",
		"public_key=a431a09eb205f2a2e0dcc9c6e69324899d4ba8f9c501c74c3b13708fe6e1d07a",
		"preshared_key=",
		"endpoint=192.0.2.10:51820",
		"persistent_keepalive_interval=25",
		"allowed_ip=0.0.0.0/0",
		"allowed_ip=::/0",
		"replace_peers=true",
	} {
		if !strings.Contains(uapi, want) {
			t.Errorf("uapi is missing %q:\n%s", want, uapi)
		}
	}
	// The file's own base64 must not appear anywhere in what is sent.
	if strings.Contains(uapi, cfg.PrivateKey) {
		t.Error("the base64 private key was passed straight through to the device")
	}
}

// Each of these brings up a device that can never work, and each fails with the
// field named rather than as "invalid argument" three layers down.
func TestParseConfigRefusesTheUnusable(t *testing.T) {
	for name, conf := range map[string]string{
		"no private key": "[Interface]\nAddress = 10.0.0.2/32\n[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = a:1",
		"no public key":  "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\n[Peer]\nEndpoint = a:1",
		"no endpoint":    "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\n[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=",
		"no address":     "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\n[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = a:1",
		"endpoint has no port": "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\n" +
			"[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = vpn.example.com",
		"key is not 32 bytes": "[Interface]\nPrivateKey = c2hvcnQ=\nAddress = 10.0.0.2/32\n" +
			"[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = a:1",
		"MTU is nonsense": "[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\nMTU = enormous\n" +
			"[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = a:1",
	} {
		if _, err := ParseConfig(conf); err == nil {
			t.Errorf("%s: ParseConfig accepted it", name)
		}
	}
}

// wg-quick files carry directives that describe a kernel interface. A userspace
// tunnel has none of those things, and a provider's file must still work.
func TestParseConfigIgnoresWhatItCannotDo(t *testing.T) {
	conf := providerConf + "\n[Interface]\nTable = off\nPostUp = iptables -A FORWARD -j ACCEPT\nSaveConfig = true\n"
	if _, err := ParseConfig(conf); err != nil {
		t.Fatalf("ParseConfig rejected a directive it should ignore: %v", err)
	}
}

func TestParseConfigDefaults(t *testing.T) {
	cfg, err := ParseConfig("[Interface]\nPrivateKey = qFRt4/gDLhF6VVjLPT9L0MkNy8yeq3S6Lc6/PXsSs2Q=\nAddress = 10.0.0.2/32\n" +
		"[Peer]\nPublicKey = pDGgnrIF8qLg3MnG5pMkiZ1LqPnFAcdMOxNwj+bh0Ho=\nEndpoint = 192.0.2.1:51820\n")
	if err != nil {
		t.Fatalf("ParseConfig: %v", err)
	}
	if cfg.MTU != DefaultMTU {
		t.Errorf("MTU = %d, want the %d default", cfg.MTU, DefaultMTU)
	}
	if len(cfg.AllowedIPs) != 1 || cfg.AllowedIPs[0].String() != "0.0.0.0/0" {
		t.Errorf("AllowedIPs = %v, want a full tunnel by default", cfg.AllowedIPs)
	}
}

// exitAddress has to read both shapes, because the URL is configurable and
// somebody will point it at the other kind.
func TestExitAddressReadsBothShapes(t *testing.T) {
	for name, body := range map[string]string{
		"cloudflare trace": "fl=123abc\nh=www.cloudflare.com\nip=203.0.113.9\nts=1.0\n",
		"bare address":     "203.0.113.9\n",
	} {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			fmt.Fprint(w, body)
		}))

		got, err := exitAddress(context.Background(), srv.Client(), srv.URL)
		if err != nil {
			t.Errorf("%s: %v", name, err)
		} else if got != "203.0.113.9" {
			t.Errorf("%s: exitAddress = %q, want 203.0.113.9", name, got)
		}
		srv.Close()
	}
}

func TestExitAddressRejectsNonsense(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		fmt.Fprint(w, "<html>your ISP's captive portal</html>")
	}))
	defer srv.Close()

	if _, err := exitAddress(context.Background(), srv.Client(), srv.URL); err == nil {
		t.Fatal("exitAddress accepted a page with no address in it")
	}
}

// --- the honest floor, for a client curator does not route -------------------

func TestExternalGuard(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		fmt.Fprint(w, "ip=203.0.113.9\n")
	}))
	defer srv.Close()

	says := func(addr string) func(context.Context) (string, error) {
		return func(context.Context) (string, error) { return addr, nil }
	}

	t.Run("same address refuses", func(t *testing.T) {
		err := External(says("203.0.113.9"), srv.URL, srv.Client(), quiet())(context.Background())
		if err == nil {
			t.Fatal("dispatch was allowed to a client on curator's own exit address")
		}
		if !strings.Contains(err.Error(), "203.0.113.9") {
			t.Errorf("err = %q, want it to name the address", err)
		}
		// The claim has to stay inside what equality actually proves. A machine
		// that is itself behind a VPN produces this reading while being
		// tunnelled, so "it has no VPN" is a sentence this must not contain.
		if strings.Contains(err.Error(), "not behind a VPN") {
			t.Errorf("err = %q, which claims more than equal addresses prove", err)
		}
		if !strings.Contains(err.Error(), "VPN_REQUIRED=false") {
			t.Errorf("err = %q, want it to name the way out", err)
		}
	})

	// VPN_REQUIRED=false has to mean the same thing here as it does for the
	// embedded engine, and for the same person: somebody whose whole machine is
	// behind a tunnel has made the one arrangement this check cannot tell apart
	// from having none.
	t.Run("advisory downgrades a refusal to a warning", func(t *testing.T) {
		refused := External(says("203.0.113.9"), srv.URL, srv.Client(), quiet())
		if err := Advisory(refused, quiet())(context.Background()); err != nil {
			t.Errorf("Advisory still refused: %v", err)
		}
	})

	t.Run("different address passes", func(t *testing.T) {
		if err := External(says("198.51.100.7"), srv.URL, srv.Client(), quiet())(context.Background()); err != nil {
			t.Errorf("dispatch refused for a client that is clearly somewhere else: %v", err)
		}
	})

	// A client that has never talked to a swarm has nothing to report, and
	// refusing the first dispatch on a fact that only exists after one is a
	// deadlock with a security-shaped excuse.
	t.Run("unknown address passes with a warning", func(t *testing.T) {
		if err := External(says(""), srv.URL, srv.Client(), quiet())(context.Background()); err != nil {
			t.Errorf("dispatch refused for a client with no address yet: %v", err)
		}
	})

	t.Run("an unreachable client is an error, not a pass", func(t *testing.T) {
		fails := func(context.Context) (string, error) { return "", errors.New("connection refused") }
		if err := External(fails, srv.URL, srv.Client(), quiet())(context.Background()); err == nil {
			t.Fatal("a client that could not be asked was treated as protected")
		}
	})
}

// Required is the default posture with the embedded engine and no tunnel: a
// refusal that names the variable which fixes it.
func TestRequiredNamesTheVariable(t *testing.T) {
	err := Required()(context.Background())
	if err == nil {
		t.Fatal("Required allowed a dispatch")
	}
	for _, want := range []string{"VPN_CONFIG", "VPN_REQUIRED=false"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("err = %q, want it to mention %s", err, want)
		}
	}
}

// fakeTunnel drives Tunnelled without a WireGuard device. It counts exit checks,
// because the whole question about the cache is how many of them happen.
type fakeTunnel struct {
	status   Status
	err      error
	checks   int
	reads    int
	failWith error
}

func (f *fakeTunnel) Status() (Status, error) {
	f.reads++
	return f.status, f.err
}

func (f *fakeTunnel) CheckExit(context.Context, string, *http.Client) (string, error) {
	f.checks++
	if f.failWith != nil {
		return "", f.failWith
	}
	return "203.0.113.9", nil
}

// TestAStaleHandshakeInvalidatesACachedPass is the ten-minute hole.
//
// The cache returned before reading the device, so one good answer bought ten
// minutes in which a dispatch verified NOTHING — not the exit address, and not
// the free in-process read of whether the far end was still there. A tunnel that
// died a minute after the first download dispatched the next nine unprotected.
func TestAStaleHandshakeInvalidatesACachedPass(t *testing.T) {
	now := time.Now()
	tunnel := &fakeTunnel{status: Status{Endpoint: "sg701:51820", LastHandshake: now}}
	guard := Tunnelled(NewChecker(tunnel, "http://example.invalid", nil, time.Hour, quiet()))

	if err := guard(context.Background()); err != nil {
		t.Fatalf("first dispatch: %v", err)
	}
	if tunnel.checks != 1 {
		t.Fatalf("exit checks = %d after the first dispatch, want 1", tunnel.checks)
	}

	// Second dispatch, tunnel still healthy, well inside the TTL. This one
	// SHOULD be cached — the whole point of the cache is that dispatching six
	// films is not six round trips.
	if err := guard(context.Background()); err != nil {
		t.Fatalf("second dispatch: %v", err)
	}
	if tunnel.checks != 1 {
		t.Errorf("exit checks = %d, want the cache to have answered the second dispatch", tunnel.checks)
	}

	// Now the far end goes away. Still inside the one-hour TTL, and the
	// handshake is now older than REJECT_AFTER_TIME.
	tunnel.status.LastHandshake = now.Add(-HandshakeStale - time.Minute)
	tunnel.failWith = errors.New("the tunnel is not carrying traffic")

	if err := guard(context.Background()); err == nil {
		t.Error("a dispatch passed on a cached answer with a handshake older than REJECT_AFTER_TIME; " +
			"the cache is being consulted before the device is read")
	}
	if tunnel.checks != 2 {
		t.Errorf("exit checks = %d, want the stale handshake to have forced a re-prove", tunnel.checks)
	}
}

// TestAnIdleTunnelWithNoKeepaliveIsStillDispatchable is the other side, and it
// is the one that would break working installs if Fresh were made a refusal.
//
// A provider config without PersistentKeepalive leaves an unused tunnel with a
// handshake hours old. It is not dead: the first dial forces a rekey and it
// succeeds. Handshaken stays the refusal; Fresh only invalidates the cache.
func TestAnIdleTunnelWithNoKeepaliveIsStillDispatchable(t *testing.T) {
	tunnel := &fakeTunnel{status: Status{
		Endpoint:      "sg701:51820",
		LastHandshake: time.Now().Add(-4 * time.Hour),
	}}

	if err := Tunnelled(NewChecker(tunnel, "http://example.invalid", nil, 0, quiet()))(context.Background()); err != nil {
		t.Errorf("an idle tunnel refused a dispatch: %v — the first dial rekeys, and refusing here "+
			"breaks every install whose provider config omits PersistentKeepalive", err)
	}
	if tunnel.checks != 1 {
		t.Errorf("exit checks = %d, want the stale handshake to have been re-proved rather than refused", tunnel.checks)
	}
}

// TestATunnelThatHasNeverHandshakenIsRefused pins that the two tests above did
// not soften the actual refusal.
func TestATunnelThatHasNeverHandshakenIsRefused(t *testing.T) {
	tunnel := &fakeTunnel{status: Status{Endpoint: "sg701:51820"}}

	err := Tunnelled(NewChecker(tunnel, "http://example.invalid", nil, 0, quiet()))(context.Background())
	if err == nil {
		t.Fatal("a tunnel that has never handshaken allowed a dispatch")
	}
	if !strings.Contains(err.Error(), "sg701:51820") {
		t.Errorf("err = %q, want it to name the endpoint that never answered", err)
	}
	if tunnel.checks != 0 {
		t.Error("the exit address was checked through a tunnel that has never handshaken")
	}
}

// TestAHandshakeHasAnAge covers the three pure readings, including the one that
// is only meaningful in the negative: a tunnel that has never handshaken has no
// age, and reporting one would draw "up 55 years ago" from a zero time.
func TestAHandshakeHasAnAge(t *testing.T) {
	now := time.Now()

	never := Status{}
	if never.Handshaken() || never.Fresh(now) || never.Age(now) != 0 {
		t.Errorf("a tunnel that has never handshaken reports handshaken=%v fresh=%v age=%v",
			never.Handshaken(), never.Fresh(now), never.Age(now))
	}

	for name, tc := range map[string]struct {
		ago       time.Duration
		wantFresh bool
	}{
		"just now":                  {ago: time.Second, wantFresh: true},
		"inside REJECT_AFTER_TIME":  {ago: HandshakeStale - time.Second, wantFresh: true},
		"outside REJECT_AFTER_TIME": {ago: HandshakeStale + time.Second, wantFresh: false},
		"an hour ago":               {ago: time.Hour, wantFresh: false},
	} {
		t.Run(name, func(t *testing.T) {
			s := Status{LastHandshake: now.Add(-tc.ago)}
			if !s.Handshaken() {
				t.Error("Handshaken = false; it must not acquire a time window, that is Fresh's job")
			}
			if got := s.Fresh(now); got != tc.wantFresh {
				t.Errorf("Fresh = %v, want %v at age %v", got, tc.wantFresh, tc.ago)
			}
			if got := s.Age(now); got != tc.ago {
				t.Errorf("Age = %v, want %v", got, tc.ago)
			}
		})
	}

	// 180 s and not a round number: REJECT_AFTER_TIME is when the far end stops
	// accepting the keypair, which is what makes an older handshake no longer
	// evidence about now.
	if HandshakeStale != 3*time.Minute {
		t.Errorf("HandshakeStale = %v, want REJECT_AFTER_TIME (180s) from the WireGuard protocol", HandshakeStale)
	}
}

// TestTheTunnelKnowsWhichAddressesAreItsOwn is half of what lets the VPN page
// say the engine's socket is inside the tunnel without either side asserting it.
func TestTheTunnelKnowsWhichAddressesAreItsOwn(t *testing.T) {
	tunnel := &Tunnel{addrs: []netip.Addr{
		netip.MustParseAddr("10.5.0.2"),
		netip.MustParseAddr("fc00:bbbb::1"),
	}}

	for name, tc := range map[string]struct {
		addr net.Addr
		want bool
	}{
		"the tunnel's v4 address": {addr: &net.UDPAddr{IP: net.ParseIP("10.5.0.2"), Port: 51820}, want: true},
		"the tunnel's v6 address": {addr: &net.UDPAddr{IP: net.ParseIP("fc00:bbbb::1"), Port: 51820}, want: true},
		"the host's LAN address":  {addr: &net.UDPAddr{IP: net.ParseIP("192.168.1.26"), Port: 51820}, want: false},
		"loopback":                {addr: &net.UDPAddr{IP: net.ParseIP("127.0.0.1"), Port: 51820}, want: false},
		"the wildcard":            {addr: &net.UDPAddr{Port: 51820}, want: false},
		"no socket at all":        {addr: nil, want: false},
	} {
		t.Run(name, func(t *testing.T) {
			if got := tunnel.Owns(tc.addr); got != tc.want {
				t.Errorf("Owns(%v) = %v, want %v", tc.addr, got, tc.want)
			}
		})
	}

	// netstack hands back a 4-in-6 form often enough that a straight comparison
	// answers false for a socket that is unmistakably inside the tunnel.
	if !tunnel.Owns(&net.UDPAddr{IP: net.ParseIP("::ffff:10.5.0.2"), Port: 51820}) {
		t.Error("a 4-in-6 form of the tunnel's own address was not recognised")
	}
}
